name: HAL UI Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        module:
          - test-configuration-batch
          - test-configuration-datasource
          - test-configuration-distributableweb
          - test-configuration-ee
          - test-configuration-iiop
          - test-configuration-interface
          - test-configuration-io
          - test-configuration-logging
          - test-configuration-mail
          - test-configuration-remoting
          - test-configuration-resourceadapter
          - test-configuration-systemproperty
          - test-configuration-transaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn --batch-mode --projects ${{ matrix.module }} --also-make -P all-tests test
