name: HAL UI Test All Modules

on:
  workflow_dispatch:
    inputs:
      hal-image:
        type: choice
        required: true
        default: quay.io/halconsole/hal
        description: 'The HAL image name'
        options:
          - quay.io/halconsole/hal
          - quay.io/halconsole/hal-development
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        module:
          - test-configuration-batch
          - test-configuration-datasource
          - test-configuration-deploymentscanner
          - test-configuration-distributableweb
          - test-configuration-ee
          - test-configuration-iiop
          - test-configuration-infinispan
          - test-configuration-interface
          - test-configuration-io
          - test-configuration-jca
          - test-configuration-jgroups
          - test-configuration-jmx
          - test-configuration-jpa
          - test-configuration-jsf
          - test-configuration-logging
          - test-configuration-mail
          - test-configuration-messaging
          - test-configuration-modcluster
          - test-configuration-path
          - test-configuration-remoting
          - test-configuration-resourceadapter
          - test-configuration-socketbinding
          - test-configuration-systemproperty
          - test-configuration-transaction
          - test-configuration-webservice
          - test-runtime-server
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Install
        run: mvn --batch-mode install
      - name: Run Tests
        run: mvn --batch-mode --projects ${{ matrix.module }} --also-make -P all-tests test -Dhal.image=${{ github.event.inputs.hal-image }}
